//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funcionario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFuncionario
    {
        public int Id_funcionario { get; set; }
        public Nullable<int> Id_setor { get; set; }
        public string nome { get; set; }
        public string cargo { get; set; }
    
        public virtual tlbSetor tlbSetor { get; set; }
    }
}
